# Generated by Django 5.2.1 on 2025-05-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodates', models.IntegerField(null=True)),
                ('availability_30', models.IntegerField(null=True)),
                ('bathrooms', models.FloatField(null=True)),
                ('bed_type', models.CharField(max_length=50, null=True)),
                ('bedrooms', models.FloatField(null=True)),
                ('beds', models.FloatField(null=True)),
                ('calculated_host_listings_count', models.IntegerField(null=True)),
                ('cancellation_policy', models.CharField(max_length=50, null=True)),
                ('guests_included', models.IntegerField(null=True)),
                ('has_availability', models.BooleanField(null=True)),
                ('host_is_superhost', models.BooleanField(null=True)),
                ('host_listings_count', models.FloatField(null=True)),
                ('instant_bookable', models.BooleanField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('maximum_nights', models.IntegerField(null=True)),
                ('number_of_reviews', models.IntegerField(null=True)),
                ('property_type', models.CharField(max_length=100, null=True)),
                ('review_scores_checkin', models.FloatField(null=True)),
                ('review_scores_communication', models.FloatField(null=True)),
                ('review_scores_location', models.FloatField(null=True)),
                ('review_scores_rating', models.FloatField(null=True)),
                ('review_scores_value', models.FloatField(null=True)),
                ('room_type', models.CharField(max_length=50, null=True)),
                ('price', models.FloatField(null=True)),
                ('amenities_wireless_internet', models.BooleanField(default=False)),
                ('amenities_fire_extinguisher', models.BooleanField(default=False)),
                ('amenities_laptop_friendly_workspace', models.BooleanField(default=False)),
                ('amenities_heating', models.BooleanField(default=False)),
                ('amenities_wheelchair_accessible', models.BooleanField(default=False)),
                ('amenities_elevator_in_building', models.BooleanField(default=False)),
                ('amenities_dogs', models.BooleanField(default=False)),
                ('amenities_cats', models.BooleanField(default=False)),
                ('amenities_washer_dryer', models.BooleanField(default=False)),
                ('amenities_smoking_allowed', models.BooleanField(default=False)),
                ('amenities_first_aid_kit', models.BooleanField(default=False)),
                ('amenities_pets_live_on_this_property', models.BooleanField(default=False)),
                ('amenities_pool', models.BooleanField(default=False)),
                ('amenities_lock_on_bedroom_door', models.BooleanField(default=False)),
                ('amenities_smoke_detector', models.BooleanField(default=False)),
                ('amenities_shampoo', models.BooleanField(default=False)),
                ('amenities_buzzer_wireless_intercom', models.BooleanField(default=False)),
                ('amenities_safety_card', models.BooleanField(default=False)),
                ('amenities_breakfast', models.BooleanField(default=False)),
                ('amenities_other_pets', models.BooleanField(default=False)),
                ('amenities_indoor_fireplace', models.BooleanField(default=False)),
                ('amenities_iron', models.BooleanField(default=False)),
                ('amenities_hair_dryer', models.BooleanField(default=False)),
                ('amenities_gym', models.BooleanField(default=False)),
                ('amenities_family_kid_friendly', models.BooleanField(default=False)),
                ('amenities_internet', models.BooleanField(default=False)),
                ('amenities_hot_tub', models.BooleanField(default=False)),
                ('amenities_washer', models.BooleanField(default=False)),
                ('amenities_dryer', models.BooleanField(default=False)),
                ('amenities_pets_allowed', models.BooleanField(default=False)),
                ('amenities_24_hour_check_in', models.BooleanField(default=False)),
                ('amenities_cable_tv', models.BooleanField(default=False)),
                ('amenities_air_conditioning', models.BooleanField(default=False)),
                ('amenities_hangers', models.BooleanField(default=False)),
                ('amenities_doorman', models.BooleanField(default=False)),
                ('amenities_essentials', models.BooleanField(default=False)),
                ('amenities_carbon_monoxide_detector', models.BooleanField(default=False)),
                ('amenities_suitable_for_events', models.BooleanField(default=False)),
                ('amenities_free_parking_on_premises', models.BooleanField(default=False)),
                ('amenities_tv', models.BooleanField(default=False)),
                ('amenities_kitchen', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Listings',
            },
        ),
    ]
